/**
 * Single source of truth for the configuration shape.
 * Spec section 8 lives here; nothing else may redeclare these types.
 */

/** Bumped on every breaking change to the shared-URL payload. */
export const CONFIG_VERSION = 1

export type PackageManager = "npm" | "pnpm" | "yarn" | "bun"

export type Inherited< T > = { mode: "inherit" } | { mode: "override"; value: T }

export type Lang = "en_us" | "ja_jp"

export interface CommonConfig {
  packageManager: PackageManager
  nodeVersion: string
  defaultBranch: string
  timezone: string
}

export interface DeployConfig {
  enabled: boolean
  target: "github-pages" | "custom"
  framework: "none" | "astro"
  branches: string[]
  manualDispatch: boolean
  nodeVersion: Inherited< string >
  packageManager: Inherited< PackageManager >
  /** null = derive from the package manager, e.g. "npm ci" */
  installCommand: string | null
  /** null = derive from the package manager, e.g. "npm run build" */
  buildCommand: string | null
  outputDir: string
  cache: boolean
  concurrency: boolean
  /** target === "custom" */
  deployCommand: string
  /** target === "custom" */
  secrets: string[]
}

export type PrType = "opened" | "synchronize" | "reopened"

export interface CiConfig {
  enabled: boolean
  targetBranches: string[]
  prTypes: PrType[]
  /** two or more entries produce a strategy.matrix */
  nodeVersions: string[]
  packageManager: Inherited< PackageManager >
  /** Enabled jobs. The auto-merge "needs:" list is built from this. */
  jobs: { lint: boolean; test: boolean; build: boolean }
  concurrency: boolean
}

export type Ecosystem =
  | "npm"
  | "pip"
  | "uv"
  | "gradle"
  | "maven"
  | "cargo"
  | "gomod"
  | "composer"
  | "bundler"
  | "nuget"
  | "docker"
  | "github-actions"
  | "terraform"
  | "swift"
  | "pub"
  | "mix"
  | "devcontainers"

export type Interval = "daily" | "weekly" | "monthly"

export type Weekday = "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday"

export type UpdateType = "minor" | "patch" | "major"

export interface AutoMergeConfig {
  enabled: boolean
  strategy: "same-workflow" | "branch-protection"
  updateTypes: UpdateType[]
  mergeMethod: "squash" | "merge" | "rebase"
  approve: boolean
}

/** One "ignore:" entry: hold back a single dependency without silencing the rest. */
export interface IgnoreRule {
  /** Package name; Dependabot also accepts "*" and glob patterns such as "@types/*". */
  dependencyName: string
  /** Empty means every update for that dependency is ignored. */
  updateTypes: UpdateType[]
}

export interface DependabotConfig {
  enabled: boolean
  ecosystems: { id: Ecosystem; directory: string }[]
  groupMinorPatch: boolean
  groupName: string
  interval: Interval
  day: Weekday
  /** "HH:mm" */
  time: string
  timezone: Inherited< string >
  openPullRequestsLimit: number
  labels: string[]
  commitMessagePrefix: string
  ignoreMajor: boolean
  /** Per-dependency holds, emitted next to the ignoreMajor wildcard. */
  ignore: IgnoreRule[]
  autoMerge: AutoMergeConfig
}

export interface OutputConfig {
  /** Emit comments into the generated files. */
  comments: boolean
  /** "ui" follows the interface language. */
  commentLanguage: "ui" | Lang
  /** Leading "Generated by ..." line. */
  generatedBy: boolean
}

export interface UiConfig {
  language: Lang
}

export interface AppState {
  ui: UiConfig
  common: CommonConfig
  ci: CiConfig
  deploy: DeployConfig
  dependabot: DependabotConfig
  output: OutputConfig
}

/** One generated file, ready to copy or zip. */
export interface GeneratedFile {
  /** ".github/workflows/deploy.yml" */
  path: string
  content: string
  /** Short name for the preview tab. */
  label: string
  /** Dictionary key explaining why the file exists, when that is not obvious. */
  noteKey?: string
}

export type Generator = ( state: AppState ) => GeneratedFile[]
